# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: KHAFAGY
# Description of the Site
description: Cyber Security Engineer || Bug Hunter
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: hacking, Template, Theme, cyber, security, cyber security, hacker
# URL for the Image of custom Favicon
favicon-url: https://media.licdn.com/dms/image/v2/D4D03AQHc80TJxip6nw/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1716141012594?e=1742428800&v=beta&t=5cqn9v2hZgTS3lRVo4eCSvg34XQVuN1NYf6KjBJ8fkE

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://www.mckinsey.com/~/media/McKinsey/Email/Shortlist/14/Shortlist_1012_CyberSecurity_600x200.aspx

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ali5afagy@gmail.com
#facebook_username: thedevslot
twitter_username: 3li_5afagy
#instagram_username: 3li_5afagy
linkedin_username: khafagy
github_username:  5afagy
#youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
#reddit_username: /
#behance_username: /
#dribbble_username: /
#spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Khafagy

# Name of the Author
author-name: Khafagy
# URL for the Image of the Author
author-image: https://media.licdn.com/dms/image/D4D03AQHc80TJxip6nw/profile-displayphoto-shrink_800_800/0/1716141012594?e=1727913600&v=beta&t=6z3ic_j4-8uYI8TNNWbFuBEgWOc8VYl9XxTHnm9P-uI
# 60 Words About the Author
author-about: "Greetings, I'm Ali Khafagy, a Computer Science graduate passionate about cybersecurity with extensive experience in penetration testing and SIEM administration. As a cybersecurity engineer, I specialize in both defensive roles (building security infrastructures, SIEM, XDR, WAF, IDS/IPS, firewalls) and offensive roles (testing software, mitigating vulnerabilities). I have discovered vulnerabilities in major companies like Nokia, Coca-Cola, IBM, LinkedIn, Airbnb, AT&T, Compass, Orange, Vodafone, and IKEA. Through this blog, I share my insights, tips, and experiences to help strengthen the cybersecurity community. In addition to my cybersecurity work, I am also a Teaching Assistant at Culture and Science City, where I lead lectures, tutorials, and course development in IoT, Networking, Databases, and Computer Architecture, fostering an engaging and interactive learning environment."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://linkedin.com/in/khafagy

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
